<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_eventos_culturales',
	'title' => 'Configuración de Eventos Culturales',
	'fields' => array(
		array(
			'key' => 'field_tab_info_evento',
			'label' => '📅 Información del Evento',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_evento_tipo',
			'label' => 'Tipo de Evento',
			'name' => 'evento_tipo',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => 'Selecciona el tipo de evento cultural',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'teatro' => 'Teatro',
				'musica' => 'Música y Conciertos',
				'danza' => 'Danza',
				'exposicion' => 'Exposición',
				'taller' => 'Taller',
				'conferencia' => 'Conferencia / Charla',
				'conversatorio' => 'Conversatorio',
				'cine' => 'Cine',
				'literario' => 'Evento Literario',
				'concurso' => 'Concurso',
				'festival' => 'Festival',
				'otro' => 'Otro',
			),
			'default_value' => 'teatro',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
			'create_options' => 0,
			'save_options' => 0,
		),
		array(
			'key' => 'field_evento_destacado',
			'label' => 'Evento Destacado',
			'name' => 'evento_destacado',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Marcar para mostrar en el slider principal',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Sí',
			'ui_off_text' => 'No',
			'message' => '',
		),
		array(
			'key' => 'field_evento_estado',
			'label' => 'Estado del Evento',
			'name' => 'evento_estado',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => 'Estado actual del evento',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'proximo' => 'Próximamente',
				'inscripcion_abierta' => 'Inscripción Abierta',
				'cupos_limitados' => 'Cupos Limitados',
				'agotado' => 'Entradas Agotadas',
				'en_curso' => 'En Curso',
				'finalizado' => 'Finalizado',
				'cancelado' => 'Cancelado',
			),
			'default_value' => 'proximo',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
			'create_options' => 0,
			'save_options' => 0,
		),
		array(
			'key' => 'field_evento_subtitulo',
			'label' => 'Subtítulo del Evento',
			'name' => 'evento_subtitulo',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Subtítulo o descripción corta',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Ej: Una experiencia única de teatro contemporáneo',
			'maxlength' => 200,
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_evento_descripcion_corta',
			'label' => 'Descripción Corta',
			'name' => 'evento_descripcion_corta',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Descripción breve del evento (se mostrará en tarjetas)',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Describe brevemente el evento...',
			'maxlength' => 300,
			'rows' => 4,
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_evento_artista',
			'label' => 'Artista / Ponente / Tallerista',
			'name' => 'evento_artista',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Nombre del artista, ponente o responsable del evento',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Ej: María García',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_evento_artista_bio',
			'label' => 'Biografía del Artista',
			'name' => 'evento_artista_bio',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Breve biografía o descripción del artista/ponente',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Biografía...',
			'maxlength' => 500,
			'rows' => 4,
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_tab_fecha_lugar',
			'label' => '📍 Fecha y Lugar',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_evento_fecha_inicio',
			'label' => 'Fecha y Hora de Inicio',
			'name' => 'evento_fecha_inicio',
			'aria-label' => '',
			'type' => 'date_time_picker',
			'instructions' => 'Cuándo comienza el evento',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y H:i',
			'return_format' => 'Y-m-d H:i:s',
			'first_day' => 1,
			'default_to_current_date' => 0,
		),
		array(
			'key' => 'field_evento_fecha_fin',
			'label' => 'Fecha y Hora de Fin',
			'name' => 'evento_fecha_fin',
			'aria-label' => '',
			'type' => 'date_time_picker',
			'instructions' => 'Cuándo termina el evento (opcional)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y H:i',
			'return_format' => 'Y-m-d H:i:s',
			'first_day' => 1,
			'default_to_current_date' => 0,
		),
		array(
			'key' => 'field_evento_duracion',
			'label' => 'Duración Estimada',
			'name' => 'evento_duracion',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Duración aproximada del evento',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Ej: 2 horas, 3 días, etc.',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_evento_multiples_fechas',
			'label' => '¿Tiene múltiples fechas?',
			'name' => 'evento_multiples_fechas',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Activar si el evento se realiza en varias fechas',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'ui' => 1,
			'message' => '',
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_evento_fechas_adicionales',
			'label' => 'Fechas Adicionales',
			'name' => 'evento_fechas_adicionales',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Lista de fechas adicionales (una por línea)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_evento_multiples_fechas',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'rows' => 4,
			'placeholder' => 'Ej:15/12/2024 - 19:0016/12/2024 - 19:0017/12/2024 - 19:00',
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_evento_lugar',
			'label' => 'Lugar del Evento',
			'name' => 'evento_lugar',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Nombre del lugar donde se realizará',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Casa de la Cultura',
			'placeholder' => 'Ej: Auditorio Principal',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_evento_direccion',
			'label' => 'Dirección',
			'name' => 'evento_direccion',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Dirección completa del lugar',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Ej: Calle Principal #123, Centro',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_evento_mapa',
			'label' => 'Enlace a Google Maps',
			'name' => 'evento_mapa',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'URL de Google Maps para ubicación',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://maps.google.com/...',
		),
		array(
			'key' => 'field_tab_entradas_cupos',
			'label' => '🎟️ Entradas y Cupos',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_evento_es_gratuito',
			'label' => '¿Evento Gratuito?',
			'name' => 'evento_es_gratuito',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Marcar si el evento es de entrada libre',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => 'Sí',
			'ui_off_text' => 'No',
			'message' => '',
		),
		array(
			'key' => 'field_evento_precio',
			'label' => 'Precio de Entrada',
			'name' => 'evento_precio',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Precio en moneda local (solo número)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_evento_es_gratuito',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'placeholder' => 'Ej: 50',
			'prepend' => '$',
			'append' => '',
		),
		array(
			'key' => 'field_evento_precios_multiples',
			'label' => 'Precios Diferenciados',
			'name' => 'evento_precios_multiples',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Si hay diferentes precios, especifícalos aquí (uno por línea)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_evento_es_gratuito',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 1,
			'rows' => 4,
			'placeholder' => 'Ej:General: $50Estudiantes: $30Tercera edad: $25',
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_evento_requiere_inscripcion',
			'label' => '¿Requiere Inscripción?',
			'name' => 'evento_requiere_inscripcion',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Activar si se requiere registro previo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'ui' => 1,
			'message' => '',
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_evento_enlace_inscripcion',
			'label' => 'Enlace de Inscripción',
			'name' => 'evento_enlace_inscripcion',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'URL del formulario de inscripción',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_evento_requiere_inscripcion',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://...',
		),
		array(
			'key' => 'field_evento_capacidad_total',
			'label' => 'Capacidad Total',
			'name' => 'evento_capacidad_total',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Número máximo de asistentes',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Ej: 200',
			'min' => 1,
			'max' => 10000,
			'step' => 1,
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_evento_cupos_disponibles',
			'label' => 'Cupos Disponibles Actuales',
			'name' => 'evento_cupos_disponibles',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Cupos restantes (actualizar manualmente)',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_evento_capacidad_total',
						'operator' => '!=empty',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Ej: 150',
			'min' => 0,
			'step' => 1,
			'max' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_evento_edad_minima',
			'label' => 'Edad Mínima',
			'name' => 'evento_edad_minima',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Edad mínima para asistir (opcional)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '34',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Ej: 18',
			'min' => 0,
			'max' => 100,
			'step' => 1,
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_tab_multimedia',
			'label' => '🎨 Multimedia',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_evento_imagen_principal',
			'label' => 'Imagen Principal / Afiche',
			'name' => 'evento_imagen_principal',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Imagen promocional del evento (Recomendado: 1200x630px)',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => 800,
			'min_height' => 600,
			'max_size' => 2,
			'mime_types' => 'jpg,jpeg,png,webp',
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
		),
		array(
			'key' => 'field_evento_imagen_banner',
			'label' => 'Banner / Portada',
			'name' => 'evento_imagen_banner',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Imagen para header (Recomendado: 1920x600px)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array(
			'key' => 'field_evento_imagen_4',
			'label' => 'Imagen Adicional 4',
			'name' => 'evento_imagen_4',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array(
			'key' => 'field_evento_imagen_5',
			'label' => 'Imagen Adicional 5',
			'name' => 'evento_imagen_5',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array(
			'key' => 'field_evento_video',
			'label' => 'Video Promocional',
			'name' => 'evento_video',
			'aria-label' => '',
			'type' => 'oembed',
			'instructions' => 'URL de YouTube, Vimeo, etc.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'width' => '',
			'height' => '',
		),
		array(
			'key' => 'field_tab_info_adicional',
			'label' => 'ℹ️ Información Adicional',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_evento_programa',
			'label' => 'Programa del Evento',
			'name' => 'evento_programa',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Detalle del programa o agenda',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_evento_requisitos',
			'label' => 'Requisitos',
			'name' => 'evento_requisitos',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => 'Requisitos para asistir (uno por línea)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'cedula' => 'Cedula',
				'amabilidad' => 'Amabilidad',
				'puntualidad' => 'Puntualidad',
			),
			'default_value' => array(
			),
			'return_format' => 'value',
			'multiple' => 1,
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'ui' => 1,
			'ajax' => 1,
			'create_options' => 1,
			'save_options' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_evento_incluye',
			'label' => '¿Qué Incluye?',
			'name' => 'evento_incluye',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => 'Qué está incluido en el evento',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'refrigerio' => 'Refrigerio',
				'material_didactico' => 'Material Didáctico',
				'certificado' => 'Certificado',
			),
			'default_value' => array(
			),
			'return_format' => 'value',
			'multiple' => 1,
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'ui' => 1,
			'ajax' => 1,
			'create_options' => 1,
			'save_options' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_evento_archivo_programa',
			'label' => 'Programa (PDF)',
			'name' => 'evento_archivo_programa',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => 'Programa en PDF para descargar',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'max_size' => 5,
			'mime_types' => 'pdf',
			'min_size' => 0,
		),
		array(
			'key' => 'field_evento_archivo_adicional',
			'label' => 'Archivo Adicional',
			'name' => 'evento_archivo_adicional',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => 'Otro archivo relacionado',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'max_size' => 5,
			'mime_types' => 'pdf,doc,docx,jpg,jpeg,png',
			'min_size' => 0,
		),
		array(
			'key' => 'field_evento_etiquetas',
			'label' => 'Etiquetas',
			'name' => 'evento_etiquetas',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => 'Etiquetas para categorizar el evento',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'familiar' => 'Para toda la familia',
				'adultos' => 'Solo adultos',
				'ninos' => 'Para niños',
				'jovenes' => 'Para jóvenes',
				'profesional' => 'Profesional',
				'principiantes' => 'Principiantes',
				'avanzado' => 'Nivel avanzado',
				'certificado' => 'Otorga certificado',
				'al_aire_libre' => 'Al aire libre',
				'virtual' => 'Virtual/Online',
				'presencial' => 'Presencial',
			),
			'default_value' => array(
			),
			'return_format' => 'value',
			'multiple' => 1,
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'ui' => 1,
			'ajax' => 1,
			'create_options' => 1,
			'save_options' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_tab_organizacion',
			'label' => '🏢 Organización',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_evento_organizador',
			'label' => 'Organizado por',
			'name' => 'evento_organizador',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Nombre del organizador o institución',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Casa de la Cultura',
			'placeholder' => '',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_evento_patrocinadores',
			'label' => 'Patrocinadores',
			'name' => 'evento_patrocinadores',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Patrocinadores del evento (separados por coma)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Ej: Empresa A, Empresa B',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_evento_contacto_nombre',
			'label' => 'Contacto - Nombre',
			'name' => 'evento_contacto_nombre',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Nombre del responsable de contacto',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_evento_contacto_telefono',
			'label' => 'Contacto - Teléfono',
			'name' => 'evento_contacto_telefono',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '+00 000 000 000',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_evento_contacto_email',
			'label' => 'Contacto - Email',
			'name' => 'evento_contacto_email',
			'aria-label' => '',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'contacto@ejemplo.com',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_evento_redes_facebook',
			'label' => 'Facebook',
			'name' => 'evento_redes_facebook',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'Evento en Facebook',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://facebook.com/...',
		),
		array(
			'key' => 'field_evento_redes_instagram',
			'label' => 'Instagram',
			'name' => 'evento_redes_instagram',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://instagram.com/...',
		),
		array(
			'key' => 'field_evento_enlace_externo',
			'label' => 'Enlace Externo',
			'name' => 'evento_enlace_externo',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'Sitio web o página del evento',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '34',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://...',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'evento',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'excerpt',
		1 => 'discussion',
		2 => 'comments',
		3 => 'revisions',
		4 => 'author',
		5 => 'format',
		6 => 'page_attributes',
	),
	'active' => true,
	'description' => 'Campos para gestionar eventos culturales',
	'show_in_rest' => 0,
) );
} );


?>