<?php
 add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_noticias_casa_cultura',
	'title' => 'Configuración de Noticias - Casa de la Cultura',
	'fields' => array(
		array(
			'key' => 'field_tab_informacion_basica',
			'label' => '📝 Información Básica',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_noticia_destacada',
			'label' => 'Noticia Destacada',
			'name' => 'noticia_destacada',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Marcar si esta noticia debe aparecer en la sección destacada de la página principal',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Sí',
			'ui_off_text' => 'No',
			'message' => '',
		),
		array(
			'key' => 'field_noticia_urgente',
			'label' => 'Noticia Urgente',
			'name' => 'noticia_urgente',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Para noticias de última hora o comunicados importantes',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Sí',
			'ui_off_text' => 'No',
			'message' => '',
		),
		array(
			'key' => 'field_noticia_categoria',
			'label' => 'Categoría de Noticia',
			'name' => 'noticia_categoria',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => 'Selecciona la categoría principal de esta noticia',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '34',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'eventos' => 'Eventos',
				'talleres' => 'Talleres y Cursos',
				'exposiciones' => 'Exposiciones',
				'actividades' => 'Actividades Culturales',
				'comunicados' => 'Comunicados Oficiales',
				'convocatorias' => 'Convocatorias',
				'galeria' => 'Galería de Fotos',
				'premios' => 'Premios y Reconocimientos',
				'general' => 'General',
			),
			'default_value' => 'general',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
			'create_options' => 0,
			'save_options' => 0,
		),
		array(
			'key' => 'field_noticia_subtitulo',
			'label' => 'Subtítulo de la Noticia',
			'name' => 'noticia_subtitulo',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Subtítulo o bajada que complementa el título principal',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Ej: Un resumen breve de la noticia',
			'maxlength' => 200,
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_noticia_resumen',
			'label' => 'Resumen Corto',
			'name' => 'noticia_resumen',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Resumen breve de la noticia (máximo 300 caracteres) - Se mostrará en listados',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Escribe un resumen atractivo de la noticia...',
			'maxlength' => 300,
			'rows' => 4,
			'new_lines' => 'br',
		),
		array(
			'key' => 'field_noticia_etiquetas',
			'label' => 'Etiquetas Personalizadas',
			'name' => 'noticia_etiquetas',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => 'Agrega etiquetas adicionales para facilitar la búsqueda',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'musica' => 'Música',
				'teatro' => 'Teatro',
				'danza' => 'Danza',
				'literatura' => 'Literatura',
				'artes-visuales' => 'Artes Visuales',
				'fotografia' => 'Fotografía',
				'cine' => 'Cine',
				'artesanias' => 'Artesanías',
				'gastronomia' => 'Gastronomía',
				'ninos' => 'Para Niños',
				'jovenes' => 'Para Jóvenes',
				'adultos' => 'Para Adultos',
				'tercera-edad' => 'Tercera Edad',
				'familia' => 'Para toda la Familia',
				'gratuito' => 'Gratuito',
				'inscripcion' => 'Requiere Inscripción',
				'certificado' => 'Otorga Certificado',
			),
			'default_value' => array(
			),
			'allow_null' => 1,
			'multiple' => 1,
			'ui' => 1,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => 'Selecciona etiquetas',
			'create_options' => 1,
			'save_options' => 0,
		),
		array(
			'key' => 'field_tab_contenido_multimedia',
			'label' => '🎨 Contenido Multimedia',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_noticia_imagen_principal',
			'label' => 'Imagen Principal',
			'name' => 'noticia_imagen_principal',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Imagen destacada de la noticia (Recomendado: 1200x630px)',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '70',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => 800,
			'min_height' => 400,
			'max_size' => 2,
			'mime_types' => 'jpg,jpeg,png,webp',
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
		),
		array(
			'key' => 'field_noticia_credito_imagen',
			'label' => 'Crédito de Imagen',
			'name' => 'noticia_credito_imagen',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Autor o fuente de la imagen (opcional)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Ej: Foto por Juan Pérez',
			'maxlength' => 150,
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_noticia_imagen_2',
			'label' => 'Imagen Adicional 2',
			'name' => 'noticia_imagen_2',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Segunda imagen para la galería (opcional)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array(
			'key' => 'field_noticia_imagen_3',
			'label' => 'Imagen Adicional 3',
			'name' => 'noticia_imagen_3',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Tercera imagen para la galería (opcional)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array(
			'key' => 'field_noticia_imagen_4',
			'label' => 'Imagen Adicional 4',
			'name' => 'noticia_imagen_4',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Cuarta imagen para la galería (opcional)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array(
			'key' => 'field_noticia_imagen_5',
			'label' => 'Imagen Adicional 5',
			'name' => 'noticia_imagen_5',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Quinta imagen para la galería (opcional)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array(
			'key' => 'field_noticia_video',
			'label' => 'Video Incrustado',
			'name' => 'noticia_video',
			'aria-label' => '',
			'type' => 'oembed',
			'instructions' => 'Pega la URL de YouTube, Vimeo u otra plataforma para incrustar el video',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'width' => '',
			'height' => '',
		),
		array(
			'key' => 'field_noticia_contenido_adicional',
			'label' => 'Contenido Adicional',
			'name' => 'noticia_contenido_adicional',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Contenido complementario que se mostrará después del contenido principal (opcional)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_tab_archivos_enlaces',
			'label' => '📎 Archivos y Enlaces',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_noticia_archivo_1_titulo',
			'label' => 'Archivo 1 - Título',
			'name' => 'noticia_archivo_1_titulo',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Nombre descriptivo del primer archivo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Ej: Programa del evento',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_noticia_archivo_1',
			'label' => 'Archivo 1',
			'name' => 'noticia_archivo_1',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => 'Primer archivo adjunto (PDF, DOC, etc.) - Máximo 5MB',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'max_size' => 5,
			'mime_types' => 'pdf,doc,docx,xls,xlsx,jpg,jpeg,png',
			'min_size' => 0,
		),
		array(
			'key' => 'field_noticia_archivo_2_titulo',
			'label' => 'Archivo 2 - Título',
			'name' => 'noticia_archivo_2_titulo',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Nombre descriptivo del segundo archivo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Ej: Convocatoria',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_noticia_archivo_2',
			'label' => 'Archivo 2',
			'name' => 'noticia_archivo_2',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => 'Segundo archivo adjunto (opcional)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'max_size' => 5,
			'mime_types' => 'pdf,doc,docx,xls,xlsx,jpg,jpeg,png',
			'min_size' => 0,
		),
		array(
			'key' => 'field_noticia_archivo_3_titulo',
			'label' => 'Archivo 3 - Título',
			'name' => 'noticia_archivo_3_titulo',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Nombre descriptivo del tercer archivo',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Ej: Formulario de inscripción',
			'maxlength' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_noticia_archivo_3',
			'label' => 'Archivo 3',
			'name' => 'noticia_archivo_3',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => 'Tercer archivo adjunto (opcional)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'max_size' => 5,
			'mime_types' => 'pdf,doc,docx,xls,xlsx,jpg,jpeg,png',
			'min_size' => 0,
		),
		array(
			'key' => 'field_noticia_enlace_externo',
			'label' => 'Enlace Externo Principal',
			'name' => 'noticia_enlace_externo',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'URL externa relacionada con la noticia (ejemplo: formulario de inscripción, sitio del evento, etc.)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '70',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://ejemplo.com',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'noticia',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'excerpt',
		1 => 'discussion',
		2 => 'comments',
		3 => 'revisions',
		4 => 'author',
		5 => 'format',
		6 => 'page_attributes',
	),
	'active' => true,
	'description' => 'Campos para noticias - Casa de la Cultura (Simplificado)',
	'show_in_rest' => 0,
) );
} );

?>